ip: 127.0.0.1
port: 8000
pg:
  host: your_pg_host
  port: 5432
  user: postgres
  password: your_pwd
  dbname: postgres
log:
  level: debug
  color_mode: always
jwt_secret: your_jwt_secret
path_to_static_dir: your_static_file_path
path_to_cert_file: your_cert_file
path_to_cert_key: your_cert_key_file
kimi_secret: your_kimi_api_secret_key

